[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# Zangoose Functionality
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "function Blind:press_play()"
position = "after"
payload = '''
    if next(SMODS.find_card('j_rrr_zangoose')) then
        rrr_hook_copy()
    end
'''
match_indent = true


# Seviper Functionality
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.blind.name == 'The Serpent' and"
position = "before"
payload = '''
    if next(SMODS.find_card('j_rrr_seviper')) and
        G.STATE == G.STATES.DRAW_TO_HAND and
        (G.GAME.current_round.hands_played > 0 or
        G.GAME.current_round.discards_used > 0) then
            hand_space = math.min(#G.deck.cards, 3)
    end
    '''
match_indent = true

# Combee 'bee' suits Functionality
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "return self.base.suit == suit"
position = "before"
payload = '''
if rrr_bee_suit_check(self, suit) then
    return true
end
'''
match_indent = true


# FLIPS ME OFF patch
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "if self == G.hand and stay_flipped then"
position = "before"
payload = '''
if self == G.hand and self.config.type ~= 'discard' and self.config.type ~= 'deck' then
    -- Flip dat shit back
    rrr_should_flip(card)
end
'''
match_indent = true


# Custom menu redirection for pokedex menu
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "pokeui.lua"]'
pattern = "if menu and clicked.config.center.poke_multi_item then menu = 'your_collection_consumables' end"
position = "after"
payload = '''
if menu and clicked.prev_menu then menu = clicked.prev_menu end
'''
match_indent = true
times = 2